//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace xRP.Administrator.QuanLyVatTu.LoaiVatTu {
    
    
    public partial class AddOrEditLoaiVatTu {
        
        /// <summary>
        /// AddOrEditLoaiVatTu_txtMaLoai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox AddOrEditLoaiVatTu_txtMaLoai;
        
        /// <summary>
        /// AddOrEditLoaiVatTu_txtTenLoai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox AddOrEditLoaiVatTu_txtTenLoai;
        
        /// <summary>
        /// AddOrEditLoaiVatTu_txtGhiChu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox AddOrEditLoaiVatTu_txtGhiChu;
    }
}
